cat > .github/workflows/deploy.yml <<'YAML'
name: Deploy to Server
on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build with Maven
        run: ./mvnw -DskipTests package

      - name: Upload JAR
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "target/*.jar"
          target: "/opt/app/myapp/"

      - name: Switch to app.jar & restart
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e
            ls -1 /opt/app/myapp/*.jar | tail -n 1 | sudo xargs -I{} mv {} /opt/app/myapp/app.jar
            sudo systemctl restart myapp
            systemctl is-active myapp
YAML
